name: use my action
on:
  pull_request:
  issue_comment:
    types: [created]
  workflow_dispatch:
  
jobs:
  caller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: My first step
      uses: ./.github/workflows/workflow_02.yml
