name: Caller Workflow
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: ./.github/actions/called_workflow
      name: Call
