name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.username }}
          echo ${{ secrets.ACTIONS_KEY }}
