name: use my action
on: [repository_dispatch]
  
jobs:
  caller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: My first step
      uses: ./.github/workflows/workflow_02.yml
