name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
    uses: outsideris/actions-test/.github/workflows/workflow_02.yml@36f0d0aef48da832eb03a4d1d82e1705392bbfdb
    with:
      username: ooocha
    secrets:
      ACTIONS_KEY: world
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/workflow_02.yml
    with:
      username: ooocha
    secrets:
      ACTIONS_KEY: test
