name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
    uses: ./.github/workflows/workflow_02.yml
    with:
      username: ooocha
    secrets:
      ACTIONS_KEY: test
