name: use my action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  caller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: My first step
      uses: ./.github/workflows/workflow_02.yml
