name: Build

on:
  workflow_run:
    workflows: ["Trigger"]
    types:
      - completed
        
jobs:
  build:  
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Xcode
      run: |
        echo 'build completed'
#       run: |
#         xcodebuild clean test -project tutorial.xcodeproj \
#         -scheme tutorial \
#         -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
