name: Trigger
on:
  issue_comment:                                     
    types: [created, edited]
jobs:
  job01:
    if: contains(github.event.comment.body, '/build/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
      - name: say hello
        run: |
          echo 'triggered'
          exit 0
