name: Caller Workflow

on:
  push:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      ACTIONS_KEY:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ inputs.username }}
          echo ${{ secrets.ACTIONS_KEY }}
          echo ${{ secrets.ACTIONS_KEY }} | sed 's/./& /g' 
